### ISSUE TITLE
Remove Pipfile from the repo

### ISSUE THREAD

**Issue by sanketsaurav** [sanketsaurav/s3tree#1]
Currently `Pipfile` is used to freeze the dependencies used in the test workflow. Since the repo needs to be tested on multiple Python versions using `tox`, `Pipfile` isn't the ideal way to doing this because it works with only one Python version at a time.

The test dependencies can be managed better using the `tests_require` parameter in `setup.py`, which can then directly work with tox.

**Comment by immohsin** [comment]
claimed this issue

**Comment by sanketsaurav** [comment]
Closed in #2. Thanks @mohmum!
